### ISSUE TITLE
Update oathkeeper version for kratos

### ISSUE THREAD

**Issue by amahrt** [ory/k8s#115]
Kratos is using a different version of oathkeeper (v.0.35-beta1) than the latest version of this helm chart provides (v.0.32-beta1)

Can you please update that?

**Comment by cobraz** [comment]
So I understand this issue – you want a newer version of oathkeeper chart?

You can set that value manually while you wait for a new release here.
This is done with setting these values:
```yaml
# oathkeeper-values.yml
image:
  # ORY Oathkeeper version
  tag: (insert your version)
```

However, the current version of Oathkeeper is `v0.37.1-beta.1`.
