### ISSUE TITLE
adminService in hydra's values yaml causes warning

### ISSUE THREAD

**Issue by bjayanth** [ory/k8s#134]
**Describe the bug**
While installing hydra as a dependency with Helm3, there is a warning:
```
coalesce.go:196: warning: cannot overwrite table with non table for adminService (map[name:<nil> port:<nil>])
```

**To Reproduce**
Have a parent chart that depends on hydra-0.3.3 Helm chart, override some values, like the fullnameOverride.

Chart.yaml:
```
dependencies:
  - name: hydra
    version: 0.3.3
    repository: https://k8s.ory.sh/helm/charts
```

values.yaml:
```
hydra:
  fullnameOverride: &HYDRA_FULLNAME "release-hydra"
  maester:
    hydraFullnameOverride: *HYDRA_FULLNAME
    fullnameOverride: hydra-maester
```
**Expected behavior**

There is no warning while installing hydra as a dependency.

**Environment**

- Helm Version: `version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}`

**Possible Fix**
Having `adminService` as a map removes the warning.
```
# Configures controller setup
maester:
  enabled: true
  # Values for the hydra admin service arguments to hydra-maester
  adminService: {}
```
