### ISSUE TITLE
There is no oryd/hydra-login-consent-node version v1.4.6

### ISSUE THREAD

**Issue by christian-roggia** [ory/k8s#139]
**Describe the bug**

The latest version of **oryd/hydra-login-consent-node** available on docker hub is **v1.4.3**, the Helm chart of the example-idp instead is pointing to the version **v1.4.6**.

```yaml
image:
  repository: oryd/hydra-login-consent-node
  tag: v1.4.6
  pullPolicy: IfNotPresent
```

**To Reproduce**

Try to install the example-idp and watch it fail.
