### ISSUE TITLE
Installing hydra and oathkeeper in one namespace results in conflict

### ISSUE THREAD

**Issue by Morishiri** [ory/k8s#142]
**Describe the bug**

When installing `hydra` and `oathkeeper` in one namespace there is conflict regarding `maester-account`:
```
Error: serviceaccounts "maester-account" already exists
```

which, as far as I checked comes from `hydra-maester` and `oathkeeper-maester` charts.

**To Reproduce**

1. `helm create ory`
2. Add dependencies in `Chart.yaml`:
   ```
   dependencies:
   - name: hydra
     version: 0.3.4
     repository: https://k8s.ory.sh/helm/charts
   - name: oathkeeper
     version: 0.3.4
     repository: https://k8s.ory.sh/helm/charts
   ```
3. Delete `templates` directory.
4. Try `helm install ...`

**Expected behavior**

The charts are deployed successfully (or complain about missing values in `values.yaml`.

**Actual behavior**

```
Error: serviceaccounts "maester-account" already exists
```
is thrown.

**Environment**

- Version: 0.3.4
- Environment: helm3

**Additional context**

N/A
