### ISSUE TITLE
Add possibility to extend the chart deployment with mounts and annotations

### ISSUE THREAD

**Issue by nseba** [ory/k8s#162]
Currently there is no way to mount extra volumes like a secret containing TLS files. This makes it impossible without hacking the chart to provide the TLS files to hydra and use them instead of termination at the source (which is not always possible).

An easy solution would be to extend the values with two sections:
* `extraVolumes`
* `extraVolumeMounts`

The consumer of the chart could then override these from the values file and extend easily without changing the chart. This goes for all charts that at least support TLS.

Same can be done for adding custom extra annotations which are necessary if using automatic sidecar injection or multiple other scenarios. This would be done with a `extraAnnotations` section

**Comment by aeneasr** [comment]
That makes a ton of sense to me, would you be open to work on a PR for this?

**Comment by nseba** [comment]
Yes, I will create a PR in the next days, as soon as I have a bit of available time.

**Comment by JovanShandro** [comment]
Hi.  Is this issue still continuing?
I am trying to use the two sections ```extraVolumes``` and  ```extraVolumesMounts``` to add a jsonnet file needed for adding github login/signup but this doesn't seem to work. Not sure if this could be a problem with some of my yaml files.

The is the config map I have created for the jsonnet file:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: github-config
data:
  # Render the kratos config:
  "oidc.github.jsonnet": |
    local claims = {
      email_verified: false
    } + std.extVar('claims');

    {
      identity: {
        traits: {
          // Allowing unverified email addresses enables account
          // enumeration attacks, especially if the value is used for
          // e.g. verification or as a password login identifier.
          //
          // Therefore we only return the email if it (a) exists and (b) is marked verified
          // by GitHub.
          [if "email" in claims && claims.email_verified then "email" else null]: claims.email,
        },
      },
    }
```

And in my values.yml I have added the following:
```yaml
deployment:                                                                                                        
  extraVolumes:                                                                                                    
     - name: github-configuration                                                                                  
       configMap:                                                                                                  
         name: github-config                                                                                       
  extraVolumeMounts:                                                                                               
     - name: github-configuration                                                                                  
       mountPath: "/etc/config"                                                                                    
       readOnly: true 
```
But the file does not get mounted in the pod.
Is there something I am doing wrong here or is this happening because there is still no full support for the extra volumes sections?

Thank you!
