### ISSUE TITLE
Horizontal Pod Autoscaler for Hydra Helm Chart

### ISSUE THREAD

**Issue by pommelinho** [ory/k8s#194]
**Is your feature request related to a problem? Please describe.**

We would like to add an HPA for our Hydra Deployment. However there is currently no HorizontalPodAutoscaler Resource in the Hydra Helm Chart.

**Describe the solution you'd like**

Add an HPA Resource to templates like e.g.

```
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: crm
  name: {{ include "hydra-chart.fullname" . }}
  labels:
    {{- include "hydra-chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hydra-chart.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.cpuAverageValue }}
    - type: Resource
      resource:
        name: cpu
        target: 
          type: AverageValue 
          averageValue: {{ .Values.autoscaling.cpuAverageValue }}
  {{- end }}
  {{- if .Values.autoscaling.memoryAverageValue }}
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: {{ .Values.autoscaling.memoryAverageValue }}
  {{- end }}
{{- end }}
```

**Describe alternatives you've considered**

Fork from ory/k8s and add HPA.yaml in own repo.
 
**Additional context**
