### ISSUE TITLE
Oathkeeper Access Rules CRD Documentation Examples Wanted

### ISSUE THREAD

**Issue by Atharex** [ory/k8s#198]
**Is your feature request related to a problem? Please describe.**

Would be great to have an example CRD to use with Oathkeeper-maester somewhere in the documentation. 
I've tried creating one from the explanations, but failed somewhere along the way...

**Additional context**

This is what I've tried:

```
[vagrant@master1 charts]$ cat access-rules.yaml 
---
apiVersion: rules.oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: access-rule
spec:
  upstream:
    url: <upstream-service>
    preserveHost: true
  match:
    url: <upstream-service>
    methods:
      - GET
      - POST
  authenticators:
    - handler: oauth2_introspection 
      config:
        introspection_url: http://hydra-admin.hydra.svc.cluster.local:4445/oauth2/introspect 
        scope_strategy: exact 
  authorizer:
    - handler: noop
  mutators:
    - handler: noop
  errors:
    - handler: json

[vagrant@master1 charts]$ kubectl apply -n oathkeeper -f access-rules.yaml
error: unable to recognize "access-rules.yaml": no matches for kind "Rule" in version "rules.oathkeeper.ory.sh/v1alpha1"
```

What is the proper way to create these CRD access rules?

**Comment by christian-roggia** [comment]
There is an open issue for oathkeeper CDRs: https://github.com/ory/oathkeeper-maester/issues/43

This is an example of oathkeeper rule we were trying to set up via CDR, it should be correct syntactically. It doesn't deploy successfully because of the issue mentioned before (we don't use the upstream as we use Istio to route traffic).

I believe that your error is in the `apiVersion` which should be set to `oathkeeper.ory.sh/v1alpha1`.

```
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: discuss-animeshon-com
  namespace: oathkeeper
spec:
  authenticators:
  - handler: noop
  authorizer:
    handler: allow
  mutators:
  - handler: noop
  match:
    url: <{https,http}>://discuss.animeshon.com/<**>
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "HEAD"]
```
