### ISSUE TITLE
Config for email templates in kratos Helm chart

### ISSUE THREAD

**Issue by sebastianvoss** [ory/k8s#217]
Currently it seems to be not possible to configure email templates in the Helm chart to customize the content of the emails kratos is sending for verification and recovery. It would be nice to have the possibility to configure this in `values.yam`.

Proposed solution:

Add those settings to `values.yaml`:
```
  emailTemplates:
    recovery:
      valid:
        subject:
        body:
      invalid:
        subject:
        body:

    verification:
      valid:
        subject:
        body:
      invalid:
        subject: 
        body:
```
If those setting are present a new `ConfigMap` can be created and mounted using an additional volume.
