### ISSUE TITLE
Make the "disable auto-generated secret" configuration consistent among chart

### ISSUE THREAD

**Issue by christian-roggia** [ory/k8s#260]
Currently (`v0.11.0`), the configuration to disable the auto-generated secrets is not consistent among charts:

_Oathkeeper_
```yaml
secret:
  manage: false
  name: oathkeeper-secrets
```

_Kratos_
```yaml
secret:
  enabled: false
  nameOverride: kratos-secrets
```

_Keto_
```yaml
secret:
  enabled: false
  nameOverride: keto-secrets
```

_Hydra_
```yaml
hydra:
  existingSecret: hydra-secrets
```
