### ISSUE TITLE
Better docs for charts

### ISSUE THREAD

**Issue by Demonsthere** [ory/k8s#323]
**Is your feature request related to a problem? Please describe.**

All charts have a readme generated by [helm-docs](https://github.com/norwoodj/helm-docs/). It seems that they changed the format for description discovery, which looks like this now 

```yaml
config:
  databasesToCreate:
    # -- default database for storage of database metadata
    - postgres

    # -- database for the [hashbash](https://github.com/norwoodj/hashbash-backend-go) project
    - hashbash
```
Notice the `--` part.

**Describe the solution you'd like**

1. Update all values yamls with the new format
2. Add a CI task to generate the docs and commit into the repository 

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**
