### ISSUE TITLE
Kratos manifest is not injected with secret specified

### ISSUE THREAD

**Issue by p-null** [ory/k8s#339]
**Describe the bug**
Hi team, I could hardly believe there is something wrong on the ory side(it's probably just my stupid mistake), but I still couldn't figure out why kratos just doesn't pick up the secret i provided... after hours of trials.

- In the kraots's `values.yaml`, I set:
```yaml
  values:
    secret:
      enabled: false
      nameOverride: "kratos-secret"
    kratos:
      autoMigrate: true
 ```
with the intention that, the migration job (and kratos) will pick up the secret `kratos-secret` that i provided instead of generating a new one.

However, the provided secret is not used and a new secret `ory-kratos` was generated, with `dsn` field as empty and other fields, as we can tell from [here](https://github.com/ory/k8s/blob/master/helm/charts/kratos/templates/secrets.yaml).

**To Reproduce**

create a k8s secret:
```yaml
apiVersion: v1
data:
  dsn: blah
  secretsCookie: blah
  secretsDefault: blah
kind: Secret
metadata:
  name: kratos-secret
  namespace: ory-kratos
type: Opaque
```
then deploy kratos to the same namespace with the  `values.yaml` mentioned above, and set appropriate `deployment.volumeMounts` (probably doesn't matter here)

**Expected behavior**

The new secret `ory-kratos` will not be generated, and the provided secret will be used.

**Environment**

- kubernetes `1.19.13`
- kratos: `kratos-0.19.5` 

**Additional context**

Happy to provide any information for investigation. Thanks in advance!
