### ISSUE TITLE
Kratos HPA doesn't work when activating it

### ISSUE THREAD

**Issue by Sjnas** [ory/k8s#340]
**Describe the bug**

When we add the autoscaling config and enable it we get an exception thrown during the deployment.

> unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): missing required field "target" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource

**To Reproduce**

1. Add the following configuration
 
 ```
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  ```
2. Do a helm install 

**Expected behavior**

I'm expecting the chart to install everything without an issue.

**Environment**

- Version: 0.19.5
- Environment: Minikube

**Additional context**
The issue is because the template is using [autoscaling/v2beta2](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2beta2/) which doesn't contain the `targetAverageUtilization`. That field is only present in the [autoscaling/v1](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v1/).

If we want to use autoscaling/v2beta2, we should be switching to the new format that defines the target.

```
{{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
```
