### ISSUE TITLE
Possibility to add annotations to Service Account

### ISSUE THREAD

**Issue by mirkoszy** [ory/k8s#348]
Currently there is no possibility to annotate kubernetes Service Account. Moreover it is impossible to not create SA. I am facing this issue in GCP while configuring Workload Identity. Annotation about binding k8s service account to GCP SA has to be added. [1]

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: GSA_NAME@PROJECT_ID.iam.gserviceaccount.com
  name: KSA_NAME
  namespace: K8S_NAMESPACE
```

There should be possibility to annotate k8s service account (or not create, or both).
With `helm create test` command we get the following SA definition:

```
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "test.serviceAccountName" . }}
  labels:
    {{- include "test.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
```

And values.yaml 

```
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
```

It would be great if ory-hydra helm chart support this.

[1] https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#yaml
