### ISSUE TITLE
Pre-deployed kubernetes secrets will result in a broken kratos configuration

### ISSUE THREAD

**Issue by christian-roggia** [ory/k8s#349]
**Describe the bug**

The following block does not take into account that secrets could be pre-deployed into the kubernetes cluster:

```yaml
            {{- if .Values.kratos.config.secrets.default }}
            - name: SECRETS_DEFAULT
              valueFrom:
                secretKeyRef:
                  name: {{ include "kratos.secretname" . }}
                  key: secretsDefault
            {{- end}}
            {{- if .Values.kratos.config.secrets.cookie }}
            - name: SECRETS_COOKIE
              valueFrom:
                secretKeyRef:
                  name: {{ include "kratos.secretname" . }}
                  key: secretsCookie
            {{- end}}
            {{- if .Values.kratos.config.courier.smtp.connection_uri }}
            - name: COURIER_SMTP_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "kratos.secretname" . }}
                  key: smtpConnectionURI
            {{- end}}
```

**To Reproduce**

Create an helm chart with the following configuration:
 
```yaml
# Kubernetes pre-deployed secrets.
secret:
  enabled: false
  nameOverride: kratos-secrets
```

Then deploy a kubernetes secret called `kratos-secrets` with cookies and smtp secrets set.

**Comment by fenech** [comment]
We ran into the same issue using the latest release v0.20.2

Our workaround was to set the following in `values.yaml`:
```yaml
deployment:
  environmentSecretsName: kratos-env-secret
secret:
  nameOverride: kratos-secret
kratos:
  config:
    courier:
      smtp:
        connection_uri: smtps://foo:bar@my-mailserver:1234/?skip_ssl_verify=false  # will be overridden in kratos-secret
        from_address: no-reply@example.com  # used by kratos courier
```

Then we used the "environment secrets" to set the `from_address`:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.environmentSecretsName | quote }}
type: Opaque
stringData:
  COURIER_SMTP_FROM_ADDRESS: no-reply@example.com  # stop kratos from complaining about an invalid (empty) address
```

...and finally, we set the `connection_uri` in the kratos secret:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.nameOverride }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{- with .Values.secretAnnotations }}
  {{- toYaml . | nindent 4 }}
{{- end }}
type: Opaque
data:
  smtpConnectionURI: {{ urlJoin (dict
    "scheme" "smtp"
    "userinfo" (print .Values.smtp.username ":" .Values.smtp.password)
    "host" (print .Values.smtp.host ":" .Values.smtp.port)
  ) | b64enc | quote }}
```
