### ISSUE TITLE
Kratos on openshift/k8s Unable to instantiate configuration : error=map[message:unexpected EOF]

### ISSUE THREAD

**Issue by mfiomus** [ory/k8s#366]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I just try to deploy kratos in openshift/k8s environment, somehow I got the errors when deploying it, the logs shows :
`level=fatal msg=Unable to instantiate configuration. audience=application error=map[message:unexpected EOF] service_name=Ory Kratos service_version=v0.8.0-alpha.3`

I have no idea about this error, where exactly the unexpected EOF happens. Am I missing something?

### Reproducing the bug

> 
Step to reproduce :

1. Run command : `helm repo add ory https://k8s.ory.sh/helm/charts` to add helm repository
2. Run `git clone https://github.com/ory/k8s.git`
3. Change dir to kratos helm chart
4. Edited the values.yaml
```
kratos:
  config:
    identity:
      default_schema_url: file:///etc/config/identity.schema.json
    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
      #template_override_path: /conf/courier-templates
    serve:
      public:
        port: 4433
      admin:
        port: 4434
    selfservice:
      default_browser_return_url: http://10.128.2.11:3000
      whitelisted_return_urls:
        - http://10.128.2.11:3000
      flows:
        logout:
          after:
            default_browser_return_url: http://10.128.2.11:3000
    secrets: {}
```

5. Deploy with `helm install kratos .`

### Relevant log output

```shell
level=fatal msg=Unable to instantiate configuration. audience=application error=map[message:unexpected EOF] service_name=Ory Kratos service_version=v0.8.0-alpha.3
```

### Relevant configuration

```yml
kratos:
  development: false
  # -- Enable the initialization job. Required to work with a DB
  autoMigrate: false

  # -- You can add multiple identity schemas here
  identitySchemas:
    "identity.schema.json": |
      {
        "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Person",
        "type": "object",
        "properties": {
          "traits": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email",
                "title": "E-Mail",
                "minLength": 3,
                "ory.sh/kratos": {
                  "credentials": {
                    "password": {
                      "identifier": true
                    }
                  },
                  "verification": {
                    "via": "email"
                  },
                  "recovery": {
                    "via": "email"
                  }
                }
              },
              "name": {
                "type": "object",
                "properties": {
                  "first": {
                    "title": "First Name",
                    "type": "string"
                  },
                  "last": {
                    "title": "Last Name",
                    "type": "string"
                  }
                }
              }
            },
            "required": [
              "email"
            ],
            "additionalProperties": false
          }
        }

  config:
    identity:
      default_schema_url: file:///etc/config/identity.schema.json
    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
      #template_override_path: /conf/courier-templates
    serve:
      public:
        port: 4433
      admin:
        port: 4434
    selfservice:
      default_browser_return_url: http://10.128.2.11:3000
      whitelisted_return_urls:
        - http://10.128.2.11:3000
      flows:
        logout:
          after:
            default_browser_return_url: http://10.128.2.11:3000
    secrets: {}
```

### Version

kratos v0.8.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm
