### ISSUE TITLE
kratos chart fails to start when kratos.config.ciphers.algorithm != noop

### ISSUE THREAD

**Issue by tristanls** [ory/k8s#374]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

`-kratos-courier-0` and `-kratos-67964566b9-6hqhd` pods fail to start due to configuration validation failure when helm configuration contains:
```yaml
kratos:
  config:
    ciphers: 
      algorithm: xchacha20-poly1305
```

The culprit is the following criteria in the [kratos `config.schema.json`](https://github.com/ory/kratos/blob/a307deb6779dacd2ce54e161a00d347600d2c583/embedx/config.schema.json#L2190-L2218) which _requires_ `secrets` to be present:
```json
    {
      "if": {
        "properties": {
          "ciphers" : {
            "properties": {
              "algorithm": {
                "oneOf": [
                  {
                    "const": "aes"
                  },
                  {
                    "const": "xchacha20-poly1305"
                  }
                ]
              }
            },
            "required": ["algorithm"]
          }
        },
        "required": ["ciphers"]
      },
      "then": {
        "required": ["secrets"],
        "properties": {
          "secrets": {
            "required": ["cipher"]
          }
        }
      }
    }
```

[Note that `secrets` is always removed from the configuration file in `_helpers.tpl`](https://github.com/ory/k8s/blob/12df18328dae6443910ddd3118f811e939f47c94/helm/charts/kratos/templates/_helpers.tpl#L70-L80):
```
{{/*
Generate the configmap data, redacting secrets
*/}}
{{- define "kratos.configmap" -}}
{{- $config := unset .Values.kratos.config "dsn" -}}
{{- $config := unset $config "secrets" -}}
{{- if .Values.kratos.config.courier.smtp.connection_uri -}}
{{- $config = set $config "courier" (set $config.courier "smtp" (unset $config.courier.smtp "connection_uri")) -}}
{{- end -}}
{{- toYaml $config -}}
{{- end -}}
```
[The above `kratos.configmap` is then used to create a configmap that will contain `kratos.yaml`](https://github.com/ory/k8s/blob/12df18328dae6443910ddd3118f811e939f47c94/helm/charts/kratos/templates/configmap-config.yaml#L9-L12):
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kratos.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kratos.labels" . | indent 4 }}
data:
  # Render the kratos config:
  "kratos.yaml": |
    {{- include "kratos.configmap" . | nindent 4 }}
```
[The above configmap is used to create the `-config-volume` volume](https://github.com/ory/k8s/blob/12df18328dae6443910ddd3118f811e939f47c94/helm/charts/kratos/templates/deployment.yaml#L54-L56):
```yaml
      volumes:
        - name: {{ include "kratos.name" . }}-config-volume
          configMap:
            name: {{ include "kratos.fullname" . }}-config
```
[The above config volume is then used as `/etc/config`, which provides a secret-less `/etc/config/kratos.yaml` that will fail validation](https://github.com/ory/k8s/blob/12df18328dae6443910ddd3118f811e939f47c94/helm/charts/kratos/templates/deployment.yaml#L107-L109):
```yaml
- name: {{ include "kratos.name" . }}-config-volume
  mountPath: /etc/config
  readOnly: true
```

The failure happens despite the kratos secret being created (and existing) and environment variables being correctly set from the kratos secret.

Pods start fine when algorithm is not set:
```yaml
kratos:
  config:
    ciphers: 
      algorithm: noop
```

### Reproducing the bug

1. Configure kratos with a cipher algorithm that is not `noop`:
```yaml
kratos:
  kratos:
    config:
      ciphers: 
        algorithm: xchacha20-poly1305
```
2. Attempt to deploy helm chart:
```yaml
dependencies:
  - name: kratos
    # https://k8s.ory.sh/helm/kratos.html
    repository: https://k8s.ory.sh/helm/charts/
    version: "0.21.0"
```
3. Deployment fails due to validation failures of `/etc/config/kratos.yaml` on pod startup

### Relevant log output

```shell
### -kratos-67964566b9-6hqhd pod log:
The configuration contains values or keys which are invalid:
The configuration contains values or keys which are invalid:
The configuration contains values or keys which are invalid:
secrets.cipher: <nil>
                ^-- one or more required properties are missing

time=2021-11-21T01:33:47Z level=fatal msg=Unable to instantiate configuration. audience=application error=map[message:I[#] S[#/allOf/1] allOf failed
  I[#] S[#/allOf/1/then] if-then failed
    I[#/secrets] S[#/allOf/1/then/properties/secrets/required] missing properties: "cipher"] service_name=Ory Kratos service_version=v0.8.0-alpha.3

...

### -kratos-courier-0 pod log:
{"audience":"application","file":"/go/pkg/mod/github.com/ory/x@v0.0.300/configx/provider.go:154","files":["/etc/config/kratos.yaml"],"func":"github.com/ory/x/configx.(*Provider).createProviders","level":"debug","msg":"Adding config files.","service_name":"Ory Kratos","service_version":"v0.8.0-alpha.3","time":"2021-11-21T01:34:26Z"}

The configuration contains values or keys which are invalid:
The configuration contains values or keys which are invalid:
The configuration contains values or keys which are invalid:
secrets: <nil>
         ^-- one or more required properties are missing

{"audience":"application","error":{"message":"I[#] S[#/allOf/1] allOf failed\n  I[#] S[#/allOf/1/then] if-then failed\n    I[#] S[#/allOf/1/then/required] missing properties: \"secrets\"","trace":"stack trace could not be recovered from error type *jsonschema.ValidationError"},"file":"/home/ory/driver/factory.go:26","func":"github.com/ory/kratos/driver.NewWithoutInit","level":"fatal","msg":"Unable to instantiate configuration.","service_name":"Ory Kratos","service_version":"v0.8.0-alpha.3","time":"2021-11-21T01:34:26Z"}
```

### Relevant configuration

```yml
kratos:
  config:
    ciphers: 
      algorithm: xchacha20-poly1305
  secret:
    enabled: true
    nameOverride: ""
    secretAnnotations:
      helm.sh/hook: "pre-install, pre-upgrade"
      helm.sh/hook-delete-policy: "before-hook-creation"
      helm.sh/hook-weight: "0"
      helm.sh/resource-policy: "keep"
```

### Version

0.21.0

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Kubernetes with Helm

**Comment by Demonsthere** [comment]
Hello there!
I was able to find the source of this bug:

```
secrets.cipher: <nil>
                ^-- one or more required properties are missing
```

We need to pass an additional key to the secrets secret, as currently we only support 
```yaml
data:
  dsn: cG9zdGdyZXM6Ly9vcnk6b3J5QHBvc3RncmVzcWwuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbC9vcnk/c3NsbW9kZT1kaXNhYmxlJm1heF9jb25uX2xpZmV0aW1lPTEwcw==
  secretsCookie: QktITUhSOGhvT3NLOG5wNkdKVUFzczExYnIzMXpJNHE=
  secretsDefault: WXF5OVVva3RUbWNxVnNmRjBPdllHVWJrTkh1UlRldlA=
  smtpConnectionURI: c210cHM6Ly90ZXN0OnRlc3RAbWFpbHNsdXJwZXI6MTAyNS8/c2tpcF9zc2xfdmVyaWZ5PXRydWU=
```
