### ISSUE TITLE
Unable to provide webhook api_key auth values as secret

### ISSUE THREAD

**Issue by nickperkins** [ory/k8s#401]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When a webhook requires authentication using an api key, this key has to be supplied in the kratos config file. Some other config values can be supplied via a secret and are not included in the ConfigMap generated by the Helm chart, but these values currently can not be provided in this way.

No matter how we try to configure this value in the helm chart, it will always be included in the ConfigMap.

### Reproducing the bug

Deploy kratos requiring  api_key authentication for a webhook. Example config section below:

```
    recovery:
      enabled: true
      lifespan: 1h
      ui_url: https://auth.platform/recovery
    registration:
      after:
        default_browser_return_url: https://auth.platform
        oidc:
          hooks:
          - hook: session
        password:
          hooks:
          - config:
              auth:
                config:
                  in: header
                  name: x-api-key
                  value: THIS_VALUE_SHOULD_BE_SECRET
                type: api_key
              body: file:///etc/config/register.jsonnet
              method: POST
              url: https://accounts.platform/api/webhooks/registration
            hook: web_hook
          - hook: session
```

### Version

v0.8.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

**Comment by Demonsthere** [comment]
Hi there!
I think you should be able to use our Env variables to workaround this. 
Basically, each config option can be passed as an env to ory apps, so 
```yaml
    registration:
      after:
        password:
          hooks:
          - config:
              auth:
                config:
                  value: THIS_VALUE_SHOULD_BE_SECRET
```
Would be `SELFSERVICE_FLOWS_REGISTRATION_AFTER_PASSWORD_HOOKS` (can be seen in the [Reference docs](https://www.ory.sh/docs/kratos/reference/configuration)

Now, with this you could use the `extraEnv` chart parameter to provide this configuration to be read from a secret 

```yaml
extraEnvs:
  - name: SELFSERVICE_FLOWS_REGISTRATION_AFTER_PASSWORD_HOOKS
    valueFrom:
      secretKeyRef:
        name: kratos-extra-secrets
        key: SELFSERVICE_FLOWS_REGISTRATION_AFTER_PASSWORD_HOOKS
```
