### ISSUE TITLE
Resources declaration level isn't consistent

### ISSUE THREAD

**Issue by thomasboni** [ory/k8s#402]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

In the `deployment` template, the resource specification is retrieved from root:

```yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
```

But in values file, it's located under `deployment`:

```yaml
deployment:

  [...]

  resources: {}
  #  We usually recommend not to specify default resources and to leave this as a conscious
  #  choice for the user. This also increases chances charts run on environments with little
  #  resources, such as Minikube. If you do want to specify resources, uncomment the following
  #  lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #  memory: 128Mi
```

This isn't consistent and can lead to configuration errors for users. I see two solutions:

- Update the template to search for `resources` under `deployment`: more consistent but will be a **breaking changes** for user currently uses `resrouces` at root level in their values files
- Update the default values files by putting `resources` at root level: no breaking changes for users. I'm going to do this update in a PR, let me know if it's ok for you 

### Reproducing the bug

- Use the default values file
- Update `resources` section to declare some `limits` / `requests` 
- Deploy the chart
- Resources isn't' t set in `deployment`

### Version

chart v0.21.5
