### ISSUE TITLE
Cannot set `domain` attribute of `Set-Cookie`

### ISSUE THREAD

**Issue by seunggs** [ory/k8s#407]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I'm not able to set the `Domain` attribute of the `Set-Cookie` using the configuration:

```
session:
  cookie:
    domain: my-domain.com
```

I’m using Kratos helm charts.

My auth app is on `auth.example.com` and Kratos is on `kratos.example.com` so without this attribute, I can’t seem to set the cookie properly over multiple subdomains.

### Reproducing the bug

1. Install Kratos via Helm on AWS EKS Kubernetes Cluster - exposed in `kratos.my-domain.com`
2. Run an authentication app in `auth.my-domain.com`
3. Check the Set-Cookie on calls to Kratos endpoint (e.g. `/sessions/whoami`) and no cookie gets set (and `Domain` attribute is not present in the Response `Set-Cookie`)

### Relevant configuration

```yml
session:
  cookie:
    domain: my-domain.com
```
```


### Version

v0.8.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

_No response_

**Comment by Demonsthere** [comment]
Hi there!
I have tried installing the chart with our base values + the cookies settings:

```yaml
---
autoscaling:
  enabled: false
kratos:
  autoMigrate: true
  identitySchemas:
    "identity.default.schema.json": |
      {
         "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
         "$schema": "http://json-schema.org/draft-07/schema#",
         "title": "Person",
         "type": "object",
         "properties": {
            "traits": {
               "type": "object",
               "properties": {
                  "email": {
                     "type": "string",
                     "format": "email",
                     "title": "E-Mail",
                     "ory.sh/kratos": {
                        "credentials": {
                           "password": {
                              "identifier": true
                           }
                        },
                        "recovery": {
                           "via": "email"
                        },
                        "verification": {
                           "via": "email"
                        }
                     }
                  }
               },
               "required": [
                  "email"
               ],
               "additionalProperties": false
            }
         }
      }
  config:
    dsn: "postgres://postgres:ory@postgresql.default.svc.cluster.local/ory?sslmode=disable&max_conn_lifetime=10s"
    selfservice:
      default_browser_return_url: http://127.0.0.1:4455/
      methods:
        password:
          enabled: true
    log:
      level: debug
    secrets:
      default:
        - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
        - "OG5XbmxXa3dYeGplQXpQanYxeEFuRUFa"
        - "foo bar 123 456 lorem"
        - "foo bar 123 456 lorem 1"
        - "foo bar 123 456 lorem 2"
        - "foo bar 123 456 lorem 3"
    cookies:
      domain: my-domain.com
      path: /
      same_site: Lax
    hashers:
      argon2:
        parallelism: 1
        memory: 128MB
        iterations: 2
        salt_length: 16
        key_length: 16
    identity:
      default_schema_url: file:///etc/config/identity.default.schema.json
    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
ingress:
  admin:
    enabled: true
  public:
    enabled: true
deployment:
  extraInitContainers: |
    - name: "hello-world"
      image: "alpine:latest"
      command: ["/bin/sh"]
      args: ["-c", "echo hello, world!"]
  extraContainers: |
    - name: "sidecar"
      image: "alpine:latest"
      command: ["/bin/sh"]
      args: ["-c", "sleep infinity"]
  extraArgs:
    - --sqa-opt-out
  labels:
    ory.sh/test: kratos

job:
  extraContainers: |
    - name: "sidecar"
      image: "alpine:latest"
      command: ["/bin/sh"]
      args: ["-c", "sleep 10"]

  shareProcessNamespace: true
 ```
 
 I can verify that the fields are present in the CM
 
 ```yaml
 apiVersion: v1
data:
  identity.default.schema.json: |
    {
       "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
       "$schema": "http://json-schema.org/draft-07/schema#",
       "title": "Person",
       "type": "object",
       "properties": {
          "traits": {
             "type": "object",
             "properties": {
                "email": {
                   "type": "string",
                   "format": "email",
                   "title": "E-Mail",
                   "ory.sh/kratos": {
                      "credentials": {
                         "password": {
                            "identifier": true
                         }
                      },
                      "recovery": {
                         "via": "email"
                      },
                      "verification": {
                         "via": "email"
                      }
                   }
                }
             },
             "required": [
                "email"
             ],
             "additionalProperties": false
          }
       }
    }
  kratos.yaml: |
    cookies:
      domain: my-domain.com
      path: /
      same_site: Lax
    courier:
      smtp: {}
    hashers:
      argon2:
        iterations: 2
        key_length: 16
        memory: 128MB
        parallelism: 1
        salt_length: 16
    identity:
      default_schema_url: file:///etc/config/identity.default.schema.json
    log:
      level: debug
    selfservice:
      default_browser_return_url: http://127.0.0.1:4455/
      methods:
        password:
          enabled: true
    serve:
      admin:
        port: 4434
      public:
        port: 4433
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: kratos
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kratos
    app.kubernetes.io/version: v0.8.0-alpha.3
    helm.sh/chart: kratos-0.21.8
  name: kratos-config
  namespace: default
```

Can you provide some more info on your installation/deployment? Maybe the values are passed incorrectly?
