### ISSUE TITLE
 kratos-selfservice-ui-node chart login button redirect to kratos pod name

### ISSUE THREAD

**Issue by CloudsLetter** [ory/k8s#417]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hi I'm trying to use the login and register functionality after deploying the kratos-selfservice-ui-node chart using helm, fill out the form click the button for the register and login page, it redirects to the pod name every time

### Reproducing the bug

kratos-selfservice-ui-node:
helm  install ui -n test .
kratos:
helm  install kratos-n test  .

### Relevant configuration

```yml
kratos:
  identitySchemas:
    "identity.default.schema.json": |
      {
         "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
         "$schema": "http://json-schema.org/draft-07/schema#",
         "title": "Person",
         "type": "object",
         "properties": {
            "traits": {
               "type": "object",
               "properties": {
                  "email": {
                     "type": "string",
                     "format": "email",
                     "title": "E-Mail",
                     "ory.sh/kratos": {
                        "credentials": {
                           "password": {
                              "identifier": true
                           }
                        },
                        "recovery": {
                           "via": "email"
                        },
                        "verification": {
                           "via": "email"
                        }
                     }
                  }
               },
               "required": [
                  "email"
               ],
               "additionalProperties": false
            }
         }
      }   


  autoMigrate: true
  config:
    serve:
      public:
        port: 4433
      admin:
        port: 4434    
    dsn: postgres://postgres:passowrd@host/kratos
               
    cookies:
      domain: example.com
      path: /
      same_site: Lax

    secrets:
     default:
      - Every ordinary day we spend may be a continuous miracle Every ordinary day we spend may be a continuous miracle
      - Knowing where the road is doesn't mean walking that road
    courier:
     smtp:
      connection_uri: smtps://support@test:test@test:465/?skip_ssl_verify=false
                 
     
    identity:
       default_schema_url: file:///etc/config/identity.default.schema.json

    selfservice:
      default_browser_return_url: https://home.oidc.example.com/
      whitelisted_return_urls:
        - https://home.oidc.example.com
                  
      methods:
        password:
         enabled: true

      flows:
        error:
          ui_url: https://home.oidc.example.com/error
                    
        settings:
           ui_url: https://home.oidc.example.com/settings
           privileged_session_max_age: 15m

        recovery:
           enabled: true
           ui_url: https://home.oidc.example.com/recovery

        verification:
           enabled: true
           ui_url: https://home.oidc.example.com/verification
           after:
             default_browser_return_url: https://home.oidc.example.com/

        logout:
           after:
             default_browser_return_url: https://home.oidc.example.com/log
        
        login:
           ui_url: https://home.oidc.example.com/login
           lifespan: 10m

        registration:
           lifespan: 10m
           ui_url: https://home.oidc.example.com/registration
           after:
             password:
               hooks:
                 -
                   hook: session


service:
  admin:
    enabled: true
    type: ClusterIP
    port: 80
    name: http-admin
    labels: {}
    annotations: {}
    #  kubernetes.io/ingress.class: traefik
    #  traefik.ingress.kubernetes.io/router.entrypoints: websecure
    #  traefik.ingress.kubernetes.io/router.tls: 'true'
  public:
    enabled: true
    type: ClusterIP
    port: 80
    name: http-public
    labels: {}
    annotations: {}
    #  kubernetes.io/ingress.class: traefik
    #  traefik.ingress.kubernetes.io/router.entrypoints: websecure
    #  traefik.ingress.kubernetes.io/router.tls: 'true'
 

ingress:
  admin:
    enabled: true
    className: ""
    annotations: 
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: 'true'
    hosts:
      - host: admin.oidc.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: 
      - secretName: admin.oidc.example.com
        hosts:
          - admin.oidc.example.com
  public:
    enabled: true
    className: ""
    annotations: 
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: 'true'
    hosts:
      -
        host: oidc.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: 
      - secretName: oidc.example.com
        hosts:
          - oidc.example.com


kratos-selfservice-ui-node:
# Default values for kratos-selfservice-ui-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of replicas in deployment
replicaCount: 1

# -- Deployment image settings
image:
  # SELFSERVICE image
  repository: oryd/kratos-selfservice-ui-node
  # -- ORY KRATOS VERSION
  tag: v0.8.0-alpha.3
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# -- Service configuration
service:
  type: ClusterIP
  port: 80
  # -- The service port name. Useful to set a custom service port name if it must follow a scheme (e.g. Istio)
  name: http

# -- Ingress configration
ingress:
  enabled: true
  className: ""
  annotations: 
     kubernetes.io/ingress.class: traefik
     traefik.ingress.kubernetes.io/router.entrypoints: websecure
     traefik.ingress.kubernetes.io/router.tls: 'true'
  hosts:
    - host: home.oidc.example.com
      paths: 
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: home.oidc.example.com
      hosts:
        - home.oidc.example.com

# -- Deployment level securityContext
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  privileged: false

# -- Deployment configuration
deployment:
  resources: {}
  #  We usually recommend not to specify default resources and to leave this as a conscious
  #  choice for the user. This also increases chances charts run on environments with little
  #  resources, such as Minikube. If you do want to specify resources, uncomment the following
  #  lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #  memory: 128Mi

  # -- Array of extra envs to be passed to the deployment. Kubernetes format is expected
  # - name: FOO
  #   value: BAR
  extraEnv: []
  # -- If you want to mount external volume
  # For example, mount a secret containing Certificate root CA to verify database
  # TLS connection.
  extraVolumes: []
  # - name: my-volume
  #   secret:
  #     secretName: my-secret
  extraVolumeMounts: []
  # - name: my-volume
  #   mountPath: /etc/secrets/my-secret
  #   readOnly: true

  # -- Node labels for pod assignment.
  nodeSelector: {}
  # If you do want to specify node labels, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'annotations:'.
  #   foo: bar

  # -- Configure node tolerations.
  tolerations: []

  labels: {}
  #      If you do want to specify additional labels, uncomment the following
  #      lines, adjust them as necessary, and remove the curly braces after 'labels:'.
  #      e.g.  type: app

  annotations: {}
  #      If you do want to specify annotations, uncomment the following
  #      lines, adjust them as necessary, and remove the curly braces after 'annotations:'.
  #      e.g.  sidecar.istio.io/rewriteAppHTTPProbers: "true"

  # https://github.com/kubernetes/kubernetes/issues/57601
  automountServiceAccountToken: false

affinity: {}

# -- Set this to ORY Kratos's Admin URL
kratosAdminUrl: "https://admin.oidc.example.com/"

# -- Set this to ORY Kratos's public URL
kratosPublicUrl: "https://oidc.example.com/"

# -- Set this to ORY Kratos's public URL accessible from the outside world.
kratosBrowserUrl: ""

# -- The baseUrl
baseUrl: ""

# -- The jwksUrl
jwksUrl: "http://oathkeeper-api"

projectName: "example"
```

### Version

v0.8.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm
