### ISSUE TITLE
Provide ability to get the `provider.client_secret` for OIDC providers from a secret in Kratos

### ISSUE THREAD

**Issue by deshetti** [ory/k8s#423]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently, all the OIDC providers info in Kratos needs to be added in `kratos.config.selfservice.methods.oidc.providers` that will be copied to a configmap: `kratos-config`

Issue is that for OIDC providers, we will need to add `client_secret` that will have to be pushed into the Git repository for the deployment scripts which is not secure. This value should be picked from Kubernetes secrets instead. In our case it looks like below for example:

```
kratos:
  config:
    selfservice:
      methods:
          oidc:
            enabled: true
            config:
              providers:
                - id: github
                  provider: github
                  client_id: <my_client_id>
                  client_secret: **<my_confidential_client_secret>**
                  mapper_url: http://example.com/mapper_url
                  scope:
                    - user:email
```

There is not an easy way currently in K8s to pick the values within a configmap from a secret: https://github.com/kubernetes/kubernetes/issues/79224

### Describe your ideal solution

The ideal solution is to provide a way to get the `client_secret` from a Kubernetes secret. 

Provide an option like for example how ArgoCD lets users add providers from Dex: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#2-configure-argo-cd-for-sso

```
data:
  url: https://argocd.example.com

  dex.config: |
    connectors:
      # GitHub example
      - type: github
        id: github
        name: GitHub
        config:
          clientID: aabbccddeeff00112233
          clientSecret: $<some_K8S_secret>:dex.github.clientSecret
          orgs:
          - name: your-github-org
```

ArgoCD save the above to a configmap as well but the clientSecret in the above is automatically picked up from a value 
 from a secret: **some_K8S_secret** and key: **dex.github.clientSecret**

### Workarounds or alternatives

Currently, the only workarounds are to expose this value in a repository or to have the **entire** kratos config in a secret and populate the configmap data from a secret (i have not tried this).

### Version

Kratos Chart: 0.22.2 Kratos Version: v0.9.0-alpha.2

**Comment by Demonsthere** [comment]
Hello there!
We have been seeing this problem pop up some time now. The core issue here is that Kratos, and by extend all Ory applications are meant to be platform agnostic, and your proposal would tie it to a k8s only environment. 
Currently this is is achievable with a workaround:

```yaml
# Configmap
kratos:
  config:
    selfservice:
      methods:
          oidc:
            enabled: true
            config:
              providers: []
```
# in your deployment override those values with secrets
extraEnvs:
  - name: SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS
    valueFrom:
      secretRef:
        name: my-secret
        key: oidc-config
```

This allows you to have the OIDC config in a secure secret, deployed separately and reference it in the deployment. 

Hope this helps!
