### ISSUE TITLE
Can't pass extraContainers to .deployment.extraContainers kratos helm template

### ISSUE THREAD

**Issue by justin-obn** [ory/k8s#432]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

```
$ helm version
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

I'm trying to install the kratos helm chart https://github.com/ory/k8s/tree/v0.22.2/helm/charts/kratos with `extraContainers` to my deployment, but I can't find the right way to passing them to the deployment

### Reproducing the bug

1. Paste to a `values.yaml` file
``` 
 deployment:
    serviceAccount:
      create: false
      name: kratos
    extraContainers: |
        - name: go-smtp
          image: go-smtp:latest
          ports:
            - name: smtp-port
              containerPort: 1025
              protocol: TCP
``` 
2.  Run `helm install release-name.  -f values.yaml`

### Relevant log output

```shell
//While using an `{}`
at <.Values.deployment.extraContainers>: wrong type for value; expected string; got map[string]interface {}

//While using a string with `|`
coalesce.go:220: warning: cannot overwrite table with non table for fuji-idp-test.kratos.deployment.extraContainers (map[])
```

### Relevant configuration

```yml
//While using an `{}`
  deployment:
    serviceAccount:
      create: false
      name: kratos
    extraContainers:
      name: go-smtp
      image: go-smtp:latest
      ports:
        name: smtp-port
        containerPort: 1025
        protocol: TCP

OR

//While using a string with `|`
 deployment:
    serviceAccount:
      create: false
      name: kratos
    extraContainers: |
        - name: go-smtp
          image: go-smtp:latest
          ports:
            - name: smtp-port
              containerPort: 1025
              protocol: TCP
```

### Version

v0.9.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm
