### ISSUE TITLE
Kratos' Helm points to the service's targetPort

### ISSUE THREAD

**Issue by gheibia** [ory/k8s#452]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When deploying kratos using helm, my ingress controller fails to register the services' endpoints.

### Reproducing the bug

Trying to setup Kratos using helm and `.circleci/values/kratos.yaml` value file:

```
> pwd
/Users/amir/ory-helm/.circleci/values

> helm install ory-kratos ../../helm/charts/kratos --values kratos.yaml
```

I'm using Nginx as my ingress controller. So I've modified the `values` file accordingly:

```
ingress:
  admin:
    enabled: true
    className: nginx
  public:
    enabled: true
    className: nginx
```

Once deployment is complete, I see the following in Nginx's log:

> W0708 20:42:23.348412       1 controller.go:2320] Error retrieving endpoints for the service ory-kratos-public: No port {http-public 0} in service ory-kratos-public

To fix this, I modified the `ingress-public.yaml` and `ingress-admin.yaml` files to use port 80 of the service instead of pod's ports:

```
              service:
                name: {{ $fullName }}-public
                port:
                  number: 80
```

### Version

helm

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Kubernetes with Helm
