### ISSUE TITLE
[kratos] datadog is no longer a valid tracing provider

### ISSUE THREAD

**Issue by nickperkins** [ory/k8s#503]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Kratos has switched to using [otelx](https://github.com/ory/kratos/pull/2318). This no longer supports the datadog tracing provider. Setting `provider.datadog` causes the `TRACING_PROVIDER` environment variable to be set on the deployment pod, which causes the deployment to fail.

### Reproducing the bug

Deploy the helm chart with the following values set:
```yaml
    deployment:
      tracing:
        datadog:
          enabled: true
          env: environment
          service: kratos
          useHostIP: true
      labels:
        admission.datadoghq.com/enabled: 'true'
        tags.datadoghq.com/env: environment
        tags.datadoghq.com/service: kratos
```

### Relevant log output

```shell
The configuration contains values or keys which are invalid:
tracing: map[provider:datadog]
         ^-- doesn't validate with "ory://tracing-config#"

The configuration contains values or keys which are invalid:
tracing.provider: datadog
                  ^-- value must be one of "jaeger", "zipkin"
```

### Version

v0.25.2

### On which operating system are you observing this issue?

Other

### In which environment are you deploying?

Kubernetes with Helm
