### ISSUE TITLE
kratos courier requies smtpConnectionURI to be present in the supplied secret even though it is provided in extra configuration file

### ISSUE THREAD

**Issue by jrester** [ory/k8s#525]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We are trying to deploy kratos and [inject the SMTP credentials into the containers from hashicorp vault](https://www.vaultproject.io/docs/platform/k8s/injector). As you can see in the exerpt from our `values.yaml` below, the credentials are rendered into the file `/vault/secrets/smtp.json` which should than be loaded by kratos. The problem here is that even though the `connection_uri` is defined in the configuration and could also be loaded by kratos, it fails because it is not defined in the secret.

```yaml
...
statefulSet:
  extraArgs:
    - --config
    - /vault/secrets/smtp.json
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: internal-kratos-app
    vault.hashicorp.com/agent-inject-secret-smtp.json: kv/data/external/mail
    vault.hashicorp.com/agent-inject-template-smtp.json: |
      {{- with secret "kv/data/external/mail" -}}
      { "courier": { "smtp": { "connection_uri": "smtps://{{ .Data.data.username }}:{{ .Data.data.password }}@smtp.mailprovider.com:465" } } }
      {{- end -}}
...
```

The Creation fails with the following error:
```
Error: couldn't find key smtpConnectionURI in Secret
```

### Describe your ideal solution

I can think of two solutions:
1. allow the user to supply a path to a file where the credentials can be found (e.g. add an environment variable `SMTP_CONNECTION_URI_FILE`). For reference the [default postgres docker image](https://hub.docker.com/_/postgres) does the same with e.g. `POSTGRES_PASSWORD_FILE`.
2. allow the SMTP URI to be omitted from the secret and instead read it from the config file (maybe add a special flag to indicate that the URI is defined there)

Regarding solution 2 I have read the issues concerning omitting the DSN (e.g. #416) and therefore believe that solution 1 would be a better fit. 

### Workarounds or alternatives

Manually create the secret with the `smtpConnectionURI` definied.

### Version

v0.10.1
