### ISSUE TITLE
How to overwrite `URLS_SELF_ISSUER` when using the Helm chart as dependency?

### ISSUE THREAD

**Issue by nicolacdnll** [ory/k8s#558]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We are using the Hydra Helm chart as a dependency and we would like to overwrite the `URL_SELF_ISSUER` (see [here](https://github.com/ory/k8s/blob/4fcdf3322b71b55da9903c816b15d4f89513c1fe/helm/charts/hydra/templates/deployment.yaml#L125) and [here](https://github.com/ory/k8s/blob/4987ebbe15f69881b47d79d6cd8be81acec6821d/helm/charts/hydra/templates/_helpers.tpl#L121)) via a `configMapKeyRef` so that the value can be obtained by composing some of our main values and without having to duplicate the information by manually setting the `.Values.hydra.config.urls.self.issuer`.

If we make use of the `extraEnv` like below the result is that the `URLS_SELF_ISSUER` will be set twice and k8s will throw an error.

```
    extraEnv:
      - name: URLS_SELF_ISSUER
        valueFrom:
          configMapKeyRef:
            name: api-gateway-config
            key: APIGW_ISS
```

### Describe your ideal solution

Not sure there is one.

### Workarounds or alternatives

The only workaround I could think of follows, but I would like to see if there are better ways.

Here is the workaround that could be used: edit the deployment so as to set the `extraEnv` before to set the other env variables. Basically change from this:

```yaml
          env:
            {{- $issuer := include "hydra.config.urls.issuer" . -}}
            {{- if $issuer }}
            - name: URLS_SELF_ISSUER
              value: {{ $issuer | quote }}
            {{- end }}
            [...]
            {{- if .Values.deployment.extraContainers }}
              {{- tpl .Values.deployment.extraContainers . | nindent 8 }}
            {{- end }}
```

to this:

```yaml
          env:
            {{- if .Values.deployment.extraContainers }}
                {{- tpl .Values.deployment.extraContainers . | nindent 8 }}
            {{- end }}
            {{- $issuer := include "hydra.config.urls.issuer" . -}}
            {{- if $issuer }}
            - name: URLS_SELF_ISSUER
              value: {{ $issuer | quote }}
            {{- end }}
            [...]
```

This way, users using the Hydra helm chart as dependency can set the `extraEnv` in the value like this:

```
hydra:
  enabled: true
  hydra:
    automigration:
      enabled: true
      type: initContainer
    config:
      urls:
        self:
          issuer: $CUSTOM_URLS_SELF_ISSUER
  deployment:
    extraEnv:
      - name: CUSTOM_URLS_SELF_ISSUER
        valueFrom:
          configMapKeyRef:
            name: api-gateway-config
            key: APIGW_ISS
```

### Version

0.26.5
