### ISSUE TITLE
Warning when setting a namespaces location in keto

### ISSUE THREAD

**Issue by rubenv** [ory/k8s#620]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When setting the location of an OPL file through values, I get:

```
coalesce.go:223: warning: destination for keto.keto.config.namespaces is a table. Ignoring non-table value  ([map[id:0 name:sample]])
```

### Reproducing the bug

Set the following in `values.yaml`:

```
  keto:
    config:
      namespaces:
        location: file:///etc/keto/namespaces.keto.ts
```

### Version

Chart 0.33.4

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

**Comment by rubenv** [comment]
@Demonsthere That does not work sadly, if I do that, rather than loading the file I end up with a namespace named like that.

With:
```
 keto:
    config:
      namespaces:
        location: file:///etc/keto/namespaces.keto.ts
```
I get:
```
curl localhost:8082/namespaces
{"namespaces":[{"name":"User"},{"name":"Group"}]}
```

With
```
 keto:
    config:
      namespaces:
        - name: file:///etc/keto/namespaces.keto.ts
```
I get:
```
curl localhost:8082/namespaces
{"namespaces":[{"name":"file:///etc/keto/namespaces.keto.ts"}]}
```

As you can see here, it can be an array or an object: https://github.com/ory/keto/blob/e7b107cb57ab2f8f3f2800ff06bab198e433c7f4/embedx/config.schema.json#L320-L362
