### ISSUE TITLE
Ory hydra dsn configuration through existing secret causes env var to not be defined

### ISSUE THREAD

**Issue by zyixc** [ory/k8s#655]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

DSN environment not defined for the deployments, jobs and cronjobs.

### Reproducing the bug

Predefining the hydra secret with the dsn value and not providing `hydra.config.dsn` omits the [following environment variable](https://github.com/ory/k8s/blob/master/helm/charts/hydra/templates/job-migration.yaml#L64).

This change was introduced here: https://github.com/ory/k8s/pull/509. I do not think this was intended, if `hydra.config.dsn` or `demo` are both not provided it can just be included. As this is a list of environment variables, later definitions can override the value.

### Relevant log output

```shell
level=fatal msg=dsn must be set audience=application service_name=Ory Hydra service_version=v2.1.2
```

### Version

0.37.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

### Additional Context

For now this is needed
```yaml
    secret:
      enabled: false
      nameOverride: hydra
    deployment:
      extraEnv: 
         - name: DSN
            valueFrom:
              secretKeyRef:
                name:  hydra
                key: dsn
```
