### ISSUE TITLE
hydra-maester Helm Chart pins system architecture

### ISSUE THREAD

**Issue by EllaFoxo** [ory/k8s#723]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

When I deploy Hydra with maester enabled on arm64, the Helm chart for maester attempts to pull down the image for amd64. This is incorrect and should not be pinned.

https://github.com/ory/k8s/blob/6dc683b53bb17f6978dfe0da665553b9d3ba71fc/helm/charts/hydra-maester/values.yaml#L15

### Reproducing the bug

Deploy Hydra on arm64 using the Helm chart, and with maester enabled

### Relevant log output

```shell
{
    "time": "2024-12-16T08:46:11.308491044Z",
    "stream": "stderr",
    "_p": "F",
    "log": "exec /manager: exec format error",
    "kubernetes": {
        "pod_name": "hydra-hydra-maester-xxxxxx",
        "namespace_name": "xxxxxx",
        "pod_id": "xxxxxx",
        "host": "xxxxxx",
        "container_name": "hydra-maester",
        "docker_id": "xxxxxx",
        "container_hash": "docker.io/oryd/hydra-maester@sha256:533df055890b0be34bfcb85dd62c78fa494120bfc957c41d4016e367d459a37f",
        "container_image": "docker.io/oryd/hydra-maester:v0.0.36-amd64"
    }
}
```

### Relevant configuration

```yml
ingress:
  admin:
    enabled: true
    className: alb
    hosts:
      - host: ${admin_domain}
        paths:
          - path: /
            pathType: ImplementationSpecific
  public:
    enabled: true
    className: alb
    hosts:
      - host: ${public_domain}
        paths:
          - path: /
            pathType: ImplementationSpecific

hydra:
  config:
    dsn: postgres://${urlencode(db_username)}:${urlencode(db_password)}@${db_host}:${db_port}/${db_name}
    secrets:
      system:
        ${system}
  automigration:
    enabled: true
  urls:
    self:
      issuer: https://${public_domain}/
      login: https://${root_domain}/login
```

### Version

Hydra v2.2.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm
