### ISSUE TITLE
hydra maester: DNS resolution fails when using fullnameOverride

### ISSUE THREAD

**Issue by paulbdavis** [ory/k8s#76]
**Describe the bug**

When using a fullname override that contains multiple "parts" it can cause the generated name for the admin service to fail

**To Reproduce**

Deploy the chart with the following name overrides included with the required values:

```yaml
fullnameOverride: foo-ory-hydra
hydra-maester:
  fullnameOverride: foo-ory-hydra-maester
```

**Expected behavior**

I would expect to the template in `_helpers.yaml` to first check for `.Values.adminService` for setting up the hostname and port, for example

```yaml
adminService:
  name: foo-ory-hydra-admin
  port: 9999
```

(the port number is not an issue here, as I am using the defaults, but it should not be hard coded into the maester subchart anyway, in case custom values are used for `.Values.service.admin.port` in the main chart)

Perhaps the maester stuff should be in the same chart rather than a sub chart so that these values can be shared (unless you can grab main chart values from a subchart? not totally sure)?

**Environment**

chart version 0.0.42
