### ISSUE TITLE
Secret annotations for helm hook on kratos/hydra/oathkeeper can't be deactivated

### ISSUE THREAD

**Issue by maximumG** [ory/k8s#770]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

We are using the official kratos helm chart to deploy kratos in our environment using helm chart version `v0.53.0`. This chart is deployed with helm `v3.16.4`.

This version adds some [helm hook annotations on Secrets](https://github.com/ory/k8s/blob/63cea7f05e2955c78457d2172e966cfe5dd617b4/helm/charts/kratos/values.yaml#L86-L92) in order to generate a new Secret upon each helm deployment of the chart and randomize some secrets.

We do not want these annotations to be set on Secret for lifecycle purpose while still want to the chart to create the Secret (The Secret value are coming from a external secret store).

We tried to reset this annotation by overriding the following value with `null`.

```yaml
secret:
  secretAnnotations:
    helm.sh/hook-weight: null
    helm.sh/hook: null
    helm.sh/hook-delete-policy: null
    helm.sh/resource-policy: null
```

However because of a bug in helm `v3.16.4`this annotation are not dropped when helm merges the keys using a subchart : https://github.com/helm/helm/pull/12879

Would it be possible to add this annotations as an opt-in/opt-out fashion ?

### Reproducing the bug

1. Use helm `v3.16.4`
2. Create a new YAML file to override the Secret annotations and use a subchart

* `Chart.yaml` file
```yaml
apiVersion: v2
name: kratos
version: 0.1.0
appVersion: "1.0"
type: application
keywords:
  - helm
dependencies:
  - name: kratos
    version: 0.53.0
    repository: https://k8s.ory.sh/helm/charts
```

* `values.yaml` file
```yaml
secret:
  secretAnnotations:
    helm.sh/hook-weight: null
    helm.sh/hook: null
    helm.sh/hook-delete-policy: null
    helm.sh/resource-policy: null
```

3.  Run the following commands and check the secret annotations

```bash
helm dependency build
helm template . -f values.yaml
```

### Relevant log output

```shell

```

### Relevant configuration

```yml

```

### Version

v0.53.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

### Additional Context

Hydra, Kratos and Oathkeeper helm chart hav the same behavior when dealing with Secret lifecycle
