### ISSUE TITLE
Whether templates are expanded in `extraEnv` is inconsistent

### ISSUE THREAD

**Issue by andreasots** [ory/k8s#773]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

When trying to provision databases for Hydra and Keto from my own chart I discovered that whether templates in `extraEnv` get expanded or not is inconsistent. In particular the main deployment template expands them but the automigration and janitor job templates do not. This is not the case with the Kratos chart where `extraEnv` gets expanded even in the automigration job template.

### Reproducing the bug

1. Expand the Hydra chart with the following values file:
```yaml
hydra:
  automigration:
    enabled: true

janitor:
  enabled: true

deployment:
  extraEnv:
    - name: DSN
      valueFrom:
        secretKeyRef: "{{ .Release.Name }}-db-hydra"
        key: uri
```
2. Notice that the expanded chart contains unexpanded templates:
```console
$ helm template hydra ory/hydra -f values.yaml | grep -F '{{'
                    secretKeyRef: '{{ .Release.Name }}-db-hydra'
              secretKeyRef: '{{ .Release.Name }}-db-hydra'
```
3. Expand the Keto chart with the following values file:
```yaml
keto:
  automigration:
    enabled: true

deployment:
  extraEnv:
    - name: DSN
      valueFrom:
        secretKeyRef: "{{ .Release.Name }}-db-keto"
        key: uri
```
4. Notice that the expanded chart contains unexpanded templates:
```console
$ helm template keto ory/keto -f values.yaml | grep -F '{{'
              secretKeyRef: '{{ .Release.Name }}-db-keto'
```

### Relevant log output

```shell

```

### Relevant configuration

```yml

```

### Version

chart version 0.53.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

`extraEnv` is not expanded in three places in the Hydra chart:

https://github.com/ory/k8s/blob/63cea7f05e2955c78457d2172e966cfe5dd617b4/helm/charts/hydra/templates/janitor-cron-job.yaml#L102-L104

https://github.com/ory/k8s/blob/63cea7f05e2955c78457d2172e966cfe5dd617b4/helm/charts/hydra/templates/job-migration.yaml#L74-L76

https://github.com/ory/k8s/blob/63cea7f05e2955c78457d2172e966cfe5dd617b4/helm/charts/hydra/templates/job-migrations-custom.yaml#L72-L74

And in a single place in the Keto chart:

https://github.com/ory/k8s/blob/63cea7f05e2955c78457d2172e966cfe5dd617b4/helm/charts/keto/templates/job-migration.yaml#L87-L89

Also in the example-idp and kratos-selfservice-ui-node charts `extraEnv` is not expanded at all:

https://github.com/ory/k8s/blob/63cea7f05e2955c78457d2172e966cfe5dd617b4/helm/charts/example-idp/templates/deployment.yaml#L37-L39

https://github.com/ory/k8s/blob/63cea7f05e2955c78457d2172e966cfe5dd617b4/helm/charts/kratos-selfservice-ui-node/templates/deployment.yaml#L77-L79
